### ISSUE TITLE
Hexed fecha assim que abre

### ISSUE THREAD

**Issue by vadajr** [brAthena/Client-Side#6]
Meu hexed está fechando assim que abre.
Estou usando tudo padrão.
Diffei o hexed com os diffs recomendados.

Estou usando: 2014-03-05bRagexe

Quando eu tento executar o hexed somente com a data.grf (sem ler minha a data publicada neste git) o jogo abre normalmente para o bRO.

Quando coloco para ler a data primeiro, o jogo abre e fecha, sem nenhum erro.

* Já colei todos os arquivos lua514 dentro da data
* Já tentei usando a opção no diff read data first, e sem ela (com uma custom_data.grf)

Meu clientinfo.xml está do mesmo jeito que estava quando baixei a data (nem o ip alterei ainda).
Teria que fazer alguma modificação na version ou langtype para funcionar com o hexed da data?

**Comment by snrdev** [comment]
Estou com o mesmo problema vadajr, já solucionou o problema?

**Comment by sandropf** [comment]
https://forum.brathena.org/index.php?/topic/27426-hexed-data-github-brathena/

**Comment by carloshenrq** [comment]
Corrigido em issue #8
Irei fechar esse aqui =]
